services:
  - type: web
    name: affinity-neurocare
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /design-bold.html
        destination: /design-bold.html
      - type: rewrite
        source: /design-elegant.html
        destination: /design-elegant.html
      - type: rewrite
        source: /gallery.html
        destination: /gallery.html
